openapi: 3.0.0
info:
  title: 광고 관리 API
  description: 광고 및 스케줄 관리를 위한 API 문서
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: 개발 서버

tags:
  - name: ads
    description: 광고 관리 관련 엔드포인트

paths:
  /api/ads:
    get:
      tags:
        - ads
      summary: 광고 목록 조회
      description: 카테고리와 시간에 따른 광고 목록을 조회합니다
      parameters:
        - in: query
          name: category
          schema:
            type: string
          description: 광고 카테고리 이름
        - in: query
          name: time
          schema:
            type: string
          description: 조회할 시간 (HH 형식)
      responses:
        '200':
          description: 성공적으로 광고 목록을 조회함
          content:
            application/json:
              schema:
                type: object
                properties:
                  ads:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        type:
                          type: string
                          enum: [image, video]
                        url:
                          type: string
                        duration:
                          type: integer
                        scheduledTime:
                          type: string
        '500':
          description: 서버 오류
          
    post:
      tags:
        - ads
      summary: 단일 광고 등록
      description: 새로운 광고를 등록합니다
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - type
                - url
                - duration
                - category
                - schedules
              properties:
                title:
                  type: string
                  maxLength: 100
                type:
                  type: string
                  enum: [image, video]
                url:
                  type: string
                  maxLength: 255
                duration:
                  type: integer
                category:
                  type: string
                schedules:
                  type: array
                  items:
                    type: string
                    format: time
                  example: ["09", "12", "15"]
      responses:
        '201':
          description: 광고가 성공적으로 등록됨
        '500':
          description: 서버 오류

  /api/ads/bulk:
    post:
      tags:
        - ads
      summary: 복수 광고 일괄 등록
      description: 여러 광고 이미지를 그룹으로 일괄 등록합니다
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - selectedTime
                - adGroups
              properties:
                selectedTime:
                  type: string
                  format: time
                  example: "13"
                adGroups:
                  type: array
                  items:
                    type: array
                    minItems: 2
                    maxItems: 2
                    items:
                      type: string
                  example: [
                    ["assets/img/yoajung-max.png", "assets/img/yoajung-min.png"],
                    ["assets/img/amos-max.png", "assets/img/amos-min.png"]
                  ]
      responses:
        '201':
          description: 광고들이 성공적으로 등록됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  ads:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        url:
                          type: string
                        scheduledTime:
                          type: string
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: string

  /api/ads/groups:
    get:
      tags:
        - ads
      summary: 광고 그룹 조회
      description: 특정 시간대의 광고 그룹을 조회합니다
      parameters:
        - in: query
          name: time
          required: true
          schema:
            type: string
            format: time
          description: 조회할 시간 (HH 형식)
      responses:
        '200':
          description: 성공적으로 광고 그룹을 조회함
          content:
            application/json:
              schema:
                type: object
                properties:
                  adGroups:
                    type: array
                    items:
                      type: object
                      properties:
                        maxImage:
                          type: string
                        minImage:
                          type: string
                        scheduledTime:
                          type: string
        '500':
          description: 서버 오류

  /api/ads/{id}:
    put:
      tags:
        - ads
      summary: 광고 수정
      description: 기존 광고의 정보를 수정합니다
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 수정할 광고 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 100
                type:
                  type: string
                  enum: [image, video]
                url:
                  type: string
                  maxLength: 255
                duration:
                  type: integer
                category:
                  type: string
                schedules:
                  type: array
                  items:
                    type: string
                    format: time
                is_active:
                  type: boolean
      responses:
        '200':
          description: 광고가 성공적으로 수정됨
        '404':
          description: 광고를 찾을 수 없음
        '500':
          description: 서버 오류

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        details:
          type: string