paths:
  /api/admin/dashboard:
    get:
      tags:
        - admin
      summary: 관리자 대시보드 데이터 조회
      description: 관리자 대시보드에 필요한 통계 데이터와 최근 정보들을 조회합니다
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 성공적으로 대시보드 데이터를 조회함
          content:
            application/json:
              schema:
                type: object
                properties:
                  stats:
                    type: object
                    properties:
                      totalUsers:
                        type: integer
                        description: 전체 사용자 수
                      totalAds:
                        type: integer
                        description: 활성화된 광고 수
                      totalSalons:
                        type: integer
                        description: 전체 미용실 수
                  recentUsers:
                    type: array
                    description: 최근 가입한 사용자 목록
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        email:
                          type: string
                        provider:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
                  recentAds:
                    type: array
                    description: 최근 등록된 광고 목록
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        type:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
                  recentSalons:
                    type: array
                    description: 최근 등록된 미용실 목록
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        address:
                          type: string
                        ownerName:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
        '401':
          description: 인증 실패
        '403':
          description: 권한 없음
        '500':
          description: 서버 오류

  /api/admin/users:
    get:
      tags:
        - admin
      summary: 전체 회원 목록 조회
      description: 관리자가 전체 회원 목록을 조회합니다. 페이지네이션, 검색, 필터링을 지원합니다.
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: 현재 페이지 번호
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
          description: 한 페이지당 항목 수
        - in: query
          name: lastId
          schema:
            type: integer
          description: 마지막으로 조회한 사용자의 ID (키셋 페이징)
        - in: query
          name: search
          schema:
            type: string
          description: 이름 또는 이메일 검색어
        - in: query
          name: role
          schema:
            type: string
            enum: [user, admin, superadmin]
          description: 사용자 권한 필터
        - in: query
          name: provider
          schema:
            type: string
            enum: [google, kakao, local]
          description: 로그인 제공자 필터
        - in: query
          name: startDate
          schema:
            type: string
            format: date
          description: 가입일 범위 시작일
        - in: query
          name: endDate
          schema:
            type: string
            format: date
          description: 가입일 범위 종료일
        - in: query
          name: sortBy
          schema:
            type: string
            enum: [id, name, email, createdAt, lastLogin]
            default: id
          description: 정렬 기준 필드
        - in: query
          name: sortDir
          schema:
            type: string
            enum: [ASC, DESC]
            default: DESC
          description: 정렬 방향
      responses:
        '200':
          description: 회원 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: 사용자 ID
                        email:
                          type: string
                          description: 이메일
                        name:
                          type: string
                          description: 이름
                        role:
                          type: string
                          enum: [user, admin, superadmin]
                          description: 권한
                        provider:
                          type: string
                          enum: [google, kakao, local]
                          description: 로그인 제공자
                        lastLogin:
                          type: string
                          format: date-time
                          description: 마지막 로그인 시간
                        createdAt:
                          type: string
                          format: date-time
                          description: 가입일
                        updatedAt:
                          type: string
                          format: date-time
                          description: 정보 수정일
                  pageInfo:
                    type: object
                    properties:
                      totalUsers:
                        type: integer
                        description: 전체 사용자 수
                      totalPages:
                        type: integer
                        description: 전체 페이지 수
                      currentPage:
                        type: integer
                        description: 현재 페이지 번호
                      hasNextPage:
                        type: boolean
                        description: 다음 페이지 존재 여부
                      nextPageParams:
                        type: object
                        nullable: true
                        properties:
                          lastId:
                            type: integer
                            description: 다음 페이지 시작 ID
                          search:
                            type: string
                            description: 검색어
                          role:
                            type: string
                            description: 권한 필터
                          provider:
                            type: string
                            description: 제공자 필터
                          startDate:
                            type: string
                            format: date
                            description: 시작일
                          endDate:
                            type: string
                            format: date
                            description: 종료일
                          sortBy:
                            type: string
                            description: 정렬 기준
                          sortDir:
                            type: string
                            description: 정렬 방향
                  filters:
                    type: object
                    properties:
                      search:
                        type: string
                        description: 적용된 검색어
                      role:
                        type: string
                        description: 적용된 권한 필터
                      provider:
                        type: string
                        description: 적용된 제공자 필터
                      startDate:
                        type: string
                        format: date
                        description: 적용된 시작일
                      endDate:
                        type: string
                        format: date
                        description: 적용된 종료일
                      sortBy:
                        type: string
                        description: 적용된 정렬 기준
                      sortDir:
                        type: string
                        description: 적용된 정렬 방향
        '401':
          description: 인증 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: 권한 없음 (슈퍼관리자 전용)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'