paths:
  /api/ads:
    get:
      tags:
        - ads
      summary: 광고 목록 조회
      description: 시간에 따른 광고 목록을 조회합니다
      parameters:
        - in: query
          name: time
          schema:
            type: string
          description: 조회할 시간 (HH 형식)
      responses:
        '200':
          description: 성공적으로 광고 목록을 조회함
          content:
            application/json:
              schema:
                type: object
                properties:
                  ads:
                    type: array
                    items:
                      $ref: '#/components/schemas/AdResponse'
        '500':
          description: 서버 오류
          
    post:
      tags:
        - ads
      summary: 광고 등록
      description: 새로운 광고를 파일과 함께 등록합니다
      operationId: createAd
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  description: 광고 제목
                  maxLength: 100
                maxFiles:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: 큰 사이즈의 이미지/비디오 파일들
                minFiles:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: 작은 사이즈의 이미지/비디오 파일들
                schedules:
                  type: string
                  description: 광고 노출 시간 배열 (JSON 문자열 ["10", "11", "13"])
                  example: '["10", "11", "13"]'
      responses:
        '201':
          description: 광고가 성공적으로 등록됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 광고가 성공적으로 저장되었습니다
                  ad:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      title:
                        type: string
                        example: 샘플 광고
                      media:
                        type: array
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: https://kr.object.ncloudstorage.com/bucket/1234567890-image.jpg
                            type:
                              type: string
                              enum: [image, video]
                              example: image
                            duration:
                              type: integer
                              example: 30
                            size:
                              type: string
                              enum: [min, max]
                              example: max
                            is_primary:
                              type: boolean
                              example: false
                      schedules:
                        type: array
                        items:
                          type: string
                        example: ["10:00", "11:00", "13:00"]
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 지원하지 않는 파일 형식입니다.
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 광고 저장 중 오류가 발생했습니다
                  details:
                    type: string

  /api/ads/list:
    get:
      tags:
        - ads
      summary: 광고 전체 목록 조회
      description: 모든 광고 목록을 조회합니다
      responses:
        '200':
          description: 성공적으로 광고 목록을 조회함
          content:
            application/json:
              schema:
                type: object
                properties:
                  ads:
                    type: array
                    items:
                      $ref: '#/components/schemas/AdResponse'
        '500':
          description: 서버 오류

  /api/ads/{id}:
    put:
      tags:
        - ads
      summary: 광고 수정
      description: 기존 광고의 정보를 수정합니다
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 수정할 광고 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - media
                - schedules
              properties:
                title:
                  type: string
                  maxLength: 100
                media:
                  type: array
                  items:
                    $ref: '#/components/schemas/AdMediaInput'
                schedules:
                  type: array
                  items:
                    type: string
                    format: time
                is_active:
                  type: boolean
      responses:
        '200':
          description: 광고가 성공적으로 수정됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  ad:
                    $ref: '#/components/schemas/AdResponse'
        '404':
          description: 광고를 찾을 수 없음
        '500':
          description: 서버 오류
  
  /api/ads/schedule:
    post:
      tags:
        - ads
      summary: 광고 스케줄 일괄 등록/수정
      description: 여러 광고의 스케줄을 일괄적으로 등록하거나 수정합니다
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                required:
                  - ad_id
                  - time
                properties:
                  ad_id:
                    type: integer
                    description: 광고 ID
                  time:
                    type: array
                    items:
                      type: integer
                      minimum: 0
                      maximum: 23
                    description: 스케줄 시간들 (0-23)
              example: [
                {
                  "ad_id": 1,
                  "time": [10]
                },
                {
                  "ad_id": 2,
                  "time": [10, 12, 16]
                }
              ]
      responses:
        '200':
          description: 스케줄 등록/수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "광고 스케줄이 성공적으로 저장되었습니다"
                  ads:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: 광고 ID
                        title:
                          type: string
                          description: 광고 제목
                        media:
                          type: array
                          items:
                            type: object
                            properties:
                              url:
                                type: string
                                description: 미디어 URL
                              type:
                                type: string
                                enum: [image, video]
                                description: 미디어 타입
                              duration:
                                type: integer
                                description: 재생 시간(초)
                              size:
                                type: string
                                enum: [min, max]
                                description: 광고 크기
                              is_primary:
                                type: boolean
                                description: 주 광고 여부
                        schedules:
                          type: array
                          items:
                            type: integer
                          description: 등록된 시간들 (0-23)
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "올바른 형식의 데이터가 아닙니다"
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: string

components:
  schemas:
    Ad:
      type: object
      properties:
        id:
          type: integer
          description: 광고 ID
        title:
          type: string
          description: 광고 제목
          maxLength: 100
        is_active:
          type: boolean
          description: 활성화 여부
          default: true
        media:
          type: array
          items:
            $ref: '#/components/schemas/AdMedia'
        schedules:
          type: array
          items:
            $ref: '#/components/schemas/AdSchedule'

    AdMedia:
      type: object
      properties:
        url:
          type: string
          description: 미디어 파일 URL
        type:
          type: string
          enum: [image, video]
          description: 미디어 타입
        duration:
          type: integer
          description: 재생 시간(초)
          default: 30
        size:
          type: string
          enum: [min, max]
          description: 크기 타입
        is_primary:
          type: boolean
          description: 대표 이미지 여부
          default: false

    AdSchedule:
      type: object
      properties:
        time:
          type: string
          format: time
          description: 광고 노출 시간 (HH:mm:ss)
        is_active:
          type: boolean
          description: 활성화 여부
          default: true

    AdResponse:
      type: object
      properties:
        id:
          type: integer
          description: 광고 ID
        title:
          type: string
          description: 광고 제목
        media:
          type: array
          items:
            $ref: '#/components/schemas/AdMedia'
        scheduledTime:
          type: string
          description: 스케줄된 시간 (조회 시에만 포함)
      required:
        - id
        - title
        - media

    Error:
      type: object
      properties:
        error:
          type: string
        details:
          type: string