openapi: 3.0.0
info:
  title: 광고 관리 시스템 API
  description: 광고 관리 및 사용자 인증을 위한 API 문서
  version: 1.0.0

tags:
  - name: auth
    description: 인증 관련 API
  - name: ads
    description: 광고 관리 API
  - name: salons
    description: 미용실 관리 API

paths:
  # auth.yaml 파일의 경로들을 포함
  /auth/google:
    $ref: './auth.yaml#/paths/~1auth~1google'
  /auth/google/callback:
    $ref: './auth.yaml#/paths/~1auth~1google~1callback'
  /auth/kakao:
    $ref: './auth.yaml#/paths/~1auth~1kakao'
  /auth/kakao/callback:
    $ref: './auth.yaml#/paths/~1auth~1kakao~1callback'
  /auth/logout:
    $ref: './auth.yaml#/paths/~1auth~1logout'
  /api/users/{userId}/role:
    $ref: './auth.yaml#/paths/~1api~1users~1{userId}~1role'
    
  # ads.yaml 파일의 경로들을 포함
  /api/ads:
    $ref: './ads.yaml#/paths/~1api~1ads'
  /api/ads/list:
    $ref: './ads.yaml#/paths/~1api~1ads~1list'
  /api/ads/{id}:
    $ref: './ads.yaml#/paths/~1api~1ads~1{id}'
  /api/ads/schedule:
    $ref: './ads.yaml#/paths/~1api~1ads~1schedule'

  # salon.yaml 파일의 경로들을 포함
  /api/salons:
    $ref: './salon.yaml#/paths/~1api~1salons'
  /api/salons/{salonId}:
    $ref: './salon.yaml#/paths/~1api~1salons~1{salonId}'

components:
  schemas:
    # auth.yaml의 스키마들을 포함
    User:
      $ref: './auth.yaml#/components/schemas/User'
    
    # ads.yaml의 스키마들을 포함
    Ad:
      $ref: './ads.yaml#/components/schemas/Ad'
    AdMedia:
      $ref: './ads.yaml#/components/schemas/AdMedia'
    AdSchedule:
      $ref: './ads.yaml#/components/schemas/AdSchedule'
    AdResponse:
      $ref: './ads.yaml#/components/schemas/AdResponse'
    Error:
      $ref: './ads.yaml#/components/schemas/Error'
    
    # salon.yaml의 스키마들을 포함
    Salon:
      $ref: './salon.yaml#/components/schemas/Salon'