paths:
  /api/salons:
    get:
      tags:
        - salons
      summary: 미용실 목록 조회
      description: 현재 로그인한 사용자의 미용실 목록을 조회합니다
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 성공적으로 미용실 목록을 조회함
          content:
            application/json:
              schema:
                type: object
                properties:
                  salons:
                    type: array
                    items:
                      $ref: '#/components/schemas/Salon'
        '401':
          description: 인증 실패
        '500':
          description: 서버 오류
          
    post:
      tags:
        - salons
      summary: 미용실 등록
      description: 새로운 미용실을 등록합니다
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - address
                - region_code
              properties:
                name:
                  type: string
                  description: 미용실 이름
                  maxLength: 100
                address:
                  type: string
                  description: 미용실 주소
                  maxLength: 255
                region_code:
                  type: string
                  description: 지역 코드
                  maxLength: 10
                business_hours:
                  type: string
                  description: 영업 시간
                  maxLength: 100
      responses:
        '201':
          description: 미용실이 성공적으로 등록됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  salon:
                    $ref: '#/components/schemas/Salon'
        '401':
          description: 인증 실패
        '500':
          description: 서버 오류

  /api/salons/{salonId}:
    get:
      tags:
        - salons
      summary: 미용실 상세 조회
      description: 특정 미용실의 상세 정보를 조회합니다
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: salonId
          required: true
          schema:
            type: integer
          description: 조회할 미용실 ID
      responses:
        '200':
          description: 성공적으로 미용실 정보를 조회함
          content:
            application/json:
              schema:
                type: object
                properties:
                  salon:
                    $ref: '#/components/schemas/Salon'
        '401':
          description: 인증 실패
        '404':
          description: 미용실을 찾을 수 없음
        '500':
          description: 서버 오류
          
    put:
      tags:
        - salons
      summary: 미용실 정보 수정
      description: 특정 미용실의 정보를 수정합니다
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: salonId
          required: true
          schema:
            type: integer
          description: 수정할 미용실 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 미용실 이름
                  maxLength: 100
                address:
                  type: string
                  description: 미용실 주소
                  maxLength: 255
                region_code:
                  type: string
                  description: 지역 코드
                  maxLength: 10
                business_hours:
                  type: string
                  description: 영업 시간
                  maxLength: 100
      responses:
        '200':
          description: 미용실 정보가 성공적으로 수정됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  salon:
                    $ref: '#/components/schemas/Salon'
        '401':
          description: 인증 실패
        '404':
          description: 미용실을 찾을 수 없음
        '500':
          description: 서버 오류
          
    delete:
      tags:
        - salons
      summary: 미용실 삭제
      description: 특정 미용실을 삭제합니다
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: salonId
          required: true
          schema:
            type: integer
          description: 삭제할 미용실 ID
      responses:
        '200':
          description: 미용실이 성공적으로 삭제됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: 인증 실패
        '404':
          description: 미용실을 찾을 수 없음
        '500':
          description: 서버 오류

components:
  schemas:
    Salon:
      type: object
      properties:
        id:
          type: integer
          description: 미용실 ID
        owner_id:
          type: integer
          description: 소유자 ID
        name:
          type: string
          description: 미용실 이름
        address:
          type: string
          description: 미용실 주소
        region_code:
          type: string
          description: 지역 코드
        business_hours:
          type: string
          description: 영업 시간
        created_at:
          type: string
          format: date-time
          description: 등록 일시
        updated_at:
          type: string
          format: date-time
          description: 수정 일시
      required:
        - id
        - owner_id
        - name
        - address
        - region_code