paths:
  /api/ads/salon:
    get:
      tags:
        - salonAds
      summary: 미용실 광고 목록 조회
      description: 현재 로그인한 사용자의 미용실에 등록된 광고 목록을 조회합니다
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 성공적으로 미용실 광고 목록을 조회함
          content:
            application/json:
              schema:
                type: object
                properties:
                  salons:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: 미용실 ID
                        name:
                          type: string
                          description: 미용실 이름
                        address:
                          type: string
                          description: 미용실 주소
                        business_hours:
                          type: string
                          description: 영업 시간
                        ads:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                description: 광고 ID
                              title:
                                type: string
                                description: 광고 제목
                              media:
                                type: array
                                items:
                                  $ref: '#/components/schemas/AdMedia'
        '401':
          description: 인증 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      tags:
        - salonAds
      summary: 미용실 광고 등록
      description: 특정 미용실의 새로운 광고를 등록합니다
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - title
                - salon_id
              properties:
                title:
                  type: string
                  description: 광고 제목
                  maxLength: 100
                salon_id:
                  type: integer
                  description: 미용실 ID
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: 광고 미디어 파일들 (이미지 또는 비디오)
                schedules:
                  type: string
                  description: 광고 일정 (JSON 문자열 ["10", "11", "13"])
                  example: '["10", "11", "13"]'
      responses:
        '201':
          description: 광고가 성공적으로 등록됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 광고가 성공적으로 저장되었습니다
                  ad:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: 광고 ID
                      title:
                        type: string
                        description: 광고 제목
                      type:
                        type: string
                        enum: [salon]
                        description: 광고 타입
                      salon_id:
                        type: integer
                        description: 미용실 ID
                      media:
                        type: array
                        items:
                          $ref: '#/components/schemas/AdMedia'
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 필수 입력값이 누락되었습니다
                  details:
                    type: string
                    example: 제목과 미용실 ID는 필수입니다
        '401':
          description: 인증 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: 권한 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 권한이 없습니다
                  details:
                    type: string
                    example: 해당 미용실의 소유자가 아닙니다
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/ads/salon/{id}:
    put:
      tags:
        - salonAds
      summary: 미용실 광고 수정
      description: 특정 미용실의 광고 정보와 미디어 파일을 수정합니다
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 수정할 광고 ID
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 광고 제목
                  maxLength: 100
                is_active:
                  type: boolean
                  description: 광고 활성화 여부
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: 광고 미디어 파일들 (이미지 또는 비디오)
                schedules:
                  type: string
                  description: 광고 일정 (JSON 문자열 ["10", "11", "13"])
                  example: '["10", "11", "13"]'
      responses:
        '200':
          description: 광고가 성공적으로 수정됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 광고가 성공적으로 수정되었습니다
                  ad:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: 광고 ID
                        example: 1
                      title:
                        type: string
                        description: 광고 제목
                        example: 리뉴얼 오픈 이벤트
                      type:
                        type: string
                        enum: [salon]
                        description: 광고 타입
                        example: salon
                      salon_id:
                        type: integer
                        description: 미용실 ID
                        example: 1
                      media:
                        type: array
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              description: 미디어 파일 URL
                              example: https://kr.object.ncloudstorage.com/bucket/ads/salon_1/1234567890-image.jpg
                            type:
                              type: string
                              enum: [image, video]
                              description: 미디어 타입
                              example: image
                            duration:
                              type: integer
                              description: 재생 시간(초)
                              example: 30
                            size:
                              type: string
                              enum: [min, max]
                              description: 크기 타입
                              example: min
                            is_primary:
                              type: boolean
                              description: 대표 이미지 여부
                              example: true
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 지원하지 않는 파일 형식입니다
                  details:
                    type: string
                    example: 파일 형식은 image/jpeg, image/png, image/gif, video/mp4만 지원합니다
        '401':
          description: 인증 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: 권한 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 권한이 없습니다
                  details:
                    type: string
                    example: 해당 미용실의 소유자가 아닙니다
        '404':
          description: 광고를 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 광고를 찾을 수 없습니다
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 미용실 광고 수정 중 오류가 발생했습니다
                  details:
                    type: string

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: 에러 메시지
        details:
          type: string
          description: 상세 에러 내용