paths:
  /api/subscription-plans:
    get:
      tags:
        - subscription
      summary: 구독 플랜 목록 조회
      description: 활성화된 모든 구독 플랜을 조회합니다.
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  plans:
                    type: array
                    items:
                      $ref: '#/components/schemas/SubscriptionPlan'
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/subscription-plan/{planId}:
    get:
      tags:
        - subscription
      summary: 특정 구독 플랜 조회
      description: ID로 구독 플랜을 조회합니다.
      parameters:
        - in: path
          name: planId
          required: true
          schema:
            type: integer
          description: 구독 플랜 ID
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionPlan'
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 구독 플랜을 찾을 수 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/admin/subscription-plans:
    post:
      tags:
        - subscription
        - admin
      summary: 구독 플랜 등록
      description: 새로운 구독 플랜을 등록합니다. (슈퍼 관리자 전용)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionPlanRequest'
      responses:
        '201':
          description: 플랜 등록 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  plan:
                    $ref: '#/components/schemas/SubscriptionPlan'
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: 중복된 플랜 이름
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/admin/subscription-plans/{planId}:
    put:
      tags:
        - subscription
        - admin
      summary: 구독 플랜 수정
      description: 기존 구독 플랜을 수정합니다. (슈퍼 관리자 전용)
      security:
        - bearerAuth: []
      parameters:
        - name: planId
          in: path
          required: true
          schema:
            type: integer
          description: 수정할 플랜 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionPlanUpdateRequest'
      responses:
        '200':
          description: 플랜 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  plan:
                    $ref: '#/components/schemas/SubscriptionPlan'
        '400':
          description: 잘못된 요청 또는 활성 구독이 있는 플랜 비활성화 시도
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 플랜을 찾을 수 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: 중복된 플랜 이름
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    SubscriptionPlan:
      type: object
      properties:
        id:
          type: integer
          description: 플랜 ID
        name:
          type: string
          description: 플랜 이름
          maxLength: 100
        type:
          type: string
          enum: [basic_sponsor, premium_sponsor]
          description: 플랜 타입
        price:
          type: integer
          description: 가격
          minimum: 0
        duration_months:
          type: integer
          description: 구독 기간(월)
          minimum: 1
        features:
          $ref: '#/components/schemas/PlanFeatures'
        is_active:
          type: boolean
          description: 활성화 여부
          default: true
        created_at:
          type: string
          format: date-time
          description: 생성일
        updated_at:
          type: string
          format: date-time
          description: 수정일

    PlanFeatures:
      type: object
      description: 플랜 기능
      properties:
        max_ads:
          type: integer
          description: 최대 광고 수
        max_media_per_ad:
          type: integer
          description: 광고 당 최대 미디어 수
        allowed_ad_types:
          type: array
          items:
            type: string
            enum: [image, video]
          description: 허용된 광고 타입
      required:
        - max_ads
        - max_media_per_ad
        - allowed_ad_types

    SubscriptionPlanRequest:
      type: object
      required:
        - name
        - type
        - price
        - duration_months
        - features
      properties:
        name:
          type: string
          maxLength: 100
        type:
          type: string
          enum: [basic_sponsor, premium_sponsor]
        price:
          type: integer
          minimum: 0
        duration_months:
          type: integer
          minimum: 1
        features:
          $ref: '#/components/schemas/PlanFeatures'

    SubscriptionPlanUpdateRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
        type:
          type: string
          enum: [basic_sponsor, premium_sponsor]
        price:
          type: integer
          minimum: 0
        duration_months:
          type: integer
          minimum: 1
        features:
          $ref: '#/components/schemas/PlanFeatures'
        is_active:
          type: boolean